name: Issue Assignment Bot

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  respond-to-assign-request:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null
    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.OPENWISP_BOT_APP_ID }}
          private-key: ${{ secrets.OPENWISP_BOT_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -e .[bots]

      - name: Run issue assignment bot
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          EVENT_DATA: ${{ toJson(github.event) }}
        run: |
          echo "$EVENT_DATA" > event.json
          python -m openwisp_utils.bots.auto_assign issue_assignment event.json
